export const base: string;
export const lg: string;
export const m: string;
export const size3xl: string;
export const size4xl: string;
export const sm: string;
export const xl: string;
export const xs: string;
export const xxl: string;
