import './globals.css';
import Header from '@/components/header';
import React from 'react';
import { getServerTranslations } from '@/translations/server-translations';
import { FALLBACK_LOCALE } from '@/translations/settings';
import { LocaleProps } from '@/app/[locale]/locale.props';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({ params: { locale }, children }: LocaleProps) {
  const { t } = await getServerTranslations(locale ?? FALLBACK_LOCALE);

  return (
    <>
      <html lang="en">
        <body>
          <div
            style={{
              height: '100vh',
              width: '100%',
            }}
          >
            <Header params={{ locale }} />
            {children}
          </div>
        </body>
      </html>
    </>
  );
}
